baseURL = 'https://azzouzisalma.github.io'
languageCode = "en-us"
title = "SALMA AZZOUZI"
theme = "personal-web"
copyright=""
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, I'm Salma :wave:"
  sub = "I'm a Telecommunication student at ENSEIRB-MATMECA"

[params.main]
  latestPublishHeader = "My Latest Project"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "edna-west.jpg" # - default "/images/edna-west.jpg"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/azzouzisalma"
  #twitter = "https://twitter.com/"
  linkedin = "https://www.linkedin.com/in/salma-azzouzi-1a4179205/"
  medium = "https://medium.com/"
  #codepen = "https://codepen.io/"
  #facebook = "https://www.facebook.com/"
  #instagram = "https://www.instagram.com/"
  gitlab = "https://gitlab.com/"
  keybase = "https://keybase.io/"

[params.contact]
  email = "sazzouzi@enseirb-matmeca.fr"
  text= "Email" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "blog"
  name = "Post"
  title = "Blog section"
  url = "/post/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true